version: '2'

services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - elasticsearch
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes:
      - ./target/testing/grafana-data:/var/lib/grafana

  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"

  # Monitrix, built on ELK by extending Logstash to support Heritrix logs.
  monitrix:
    image: ukwa/monitrix
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5000:5000"
      - "5044:5044"

  monitor:
    build: .
    ports:
      - "5000:5000"
