version: '2'

# Environment variables common to all deployments
env_file:
  - ./common.env

services:

  # Log and event processing for reporting/debugging (ELK stack)
  # -------------------------------------------------------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'xpack.security.enabled=false']
    ports:
      - "9200:9200"

  # Logstash with knowledge of how to parse Heritrix3 crawl log files
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    ports:
      - "9600:9600"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on: ['elasticsearch']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports:
      - "5601:5601"
    depends_on: ['elasticsearch']

  # For testing purposes
  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    volumes: 
      - './filebeat/test-logs:/heritrix/output/logs/test-logs:ro'
      - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    depends_on: ['elasticsearch']

