version: '3.2'

services:

  # Log and event processing for reporting/debugging (ELK stack)
  # -------------------------------------------------------------

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'xpack.security.enabled=false']
    ports:
      - 9200:9200

  kibana:
    image: "docker.elastic.co/kibana/kibana:5.6.3"
    command: [ "/bin/bash", "-c", "/usr/share/kibana/bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker" ]
    ports:
      - 5601:5601
    depends_on: ['elasticsearch']

  # Logstash with knowledge of how to parse Heritrix3 crawl log files
  logstash-crawl-logs:
    image: "docker.elastic.co/logstash/logstash:5.6.3"
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - ./logstash/pipelines/heritrix-crawl-log-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on: ['elasticsearch', 'kafka']

  # Logstash with knowledge of how to parse web access log files
  logstash-www-logs:
    image: "docker.elastic.co/logstash/logstash:5.6.3"
    ports:
      - 9601:9600
      - 5045:5044
    volumes:
      - ./logstash/pipelines/access-www-log-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on: ['elasticsearch', 'kafka']

  # Kafka used as main mechanism for routing data for monitoring
  # Needs a Zookeeper too
  # ----
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
