version: '3.2'

# prometheus monitoring service

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    user: "1000"
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_NAME=BL"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer"
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - /opt/data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager:alertmanager
    user: root
    volumes:
      - ./prometheus:/etc/prometheus

    # hosts referenced by docker prometheus must be detailed here
    # as OS /etc/hosts declaration not visible to container
    extra_hosts:
      - "access:192.168.45.25"
      - "bigcdx:192.168.45.21"
      - "clamd:192.168.45.87"
      - "clamd-lb1:192.168.45.50"
      - "clamd-lb2:192.168.45.51"
      - "clamd-lb3:192.168.45.52"
      - "clamd-lb4:192.168.45.54"
      - "clamd-lb5:192.168.45.55"
      - "clamd-lb6:192.168.45.56"
      - "clamd-lb7:192.168.45.57"
      - "clamd-lb8:192.168.45.58"
      - "clamd-lb9:192.168.45.59"
      - "crawler01:192.168.45.16"
      - "crawler02:192.168.45.19"
      - "crawler03:192.168.45.28"
      - "crawler04:192.168.45.12"
      - "gluster-fuse:192.168.45.109"
      - "gluster01:192.168.45.111"
      - "gluster02:192.168.45.112"
      - "gluster03:192.168.45.113"
      - "gluster04:192.168.45.114"
      - "gluster05:192.168.45.115"
      - "gluster06:192.168.45.116"
      - "gluster07:192.168.45.120"
      - "gluster08:192.168.45.121"
      - "gluster09:192.168.45.122"
      - "gluster10:192.168.45.123"
      - "gluster11:192.168.45.124"
      - "gluster12:192.168.45.125"
      - "grunt01:192.168.1.25"
      - "hdfs:192.168.45.13"
      - "hdfs-lb1:192.168.1.44"
      - "hdfs-lb2:192.168.1.45"
      - "hdfs-lb3:192.168.1.46"
      - "hdfs-lb4:192.168.1.47"
      - "hdfs-lb5:192.168.1.48"
      - "ingest:192.168.45.60"
      - "intranet:192.168.45.30"
      - "jisc03:192.168.1.57"
      - "jisc-proxy:192.168.45.70"
      - "jisc-zk01:192.168.1.62"
      - "jisc-zk02:192.168.1.63"
      - "jisc-zk03:192.168.1.64"
      - "ldukwa04:192.168.1.54"
      - "ldukwa-proxy:192.168.45.17"
      - "ldukwa-zk01:192.168.1.209"
      - "ldukwa-zk02:192.168.1.210"
      - "ldukwa-zk03:192.168.1.211"
      - "mapred:192.168.45.18"
      - "monitor:192.168.45.204"
      - "priv-gtw-n1:192.168.45.29"
      - "sh:192.168.45.2"
      - "solr1:192.168.1.71"
      - "solr2:192.168.1.72"
      - "solr-proxy:192.168.45.33"
      - "syslog:192.168.45.9"
      - "wa-www:192.168.45.10"
      - "zk1:192.168.1.81"
      - "zk2:192.168.1.82"
      - "zk3:192.168.1.83"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://monitor.wa.bl.uk:9090/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://monitor.wa.bl.uk:9093/'
