version: '3.2'

# prometheus monitoring service

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    user: "1000"
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_NAME=BL"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer"
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - /opt/data/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager:alertmanager
    user: root
    volumes:
      - ./prometheus:/etc/prometheus

    # hosts referenced by docker prometheus must be detailed here
    # as OS /etc/hosts declaration not visible to container
    extra_hosts:
      - "monitor:192.168.45.204"
      - "syslog:192.168.45.9"
      - "grunt01:192.168.1.25"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://monitor.wa.bl.uk:9090/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://monitor.wa.bl.uk:9093/'
