version: "3"

services:

  # UKWA Heritrix
  heritrix-worker:
    image: ukwa/heritrix-worker
    environment:
      - "JAVA_OPTS=-Xmx2g"
      - "CLAMD_HOST=clamd"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "KAFKA_CRAWLED_TOPIC=frequent-crawl-log"
      - "KAFKA_TOCRAWL_TOPIC=uris-to-crawl"
      - "WRENDER_ENDPOINT=http://wrender:8010/render"
      - "CDXSERVER_ENDPOINT=http://cdxserver:8080/fc"
      - "JOB_NAME=frequent"
      - "HERITRIX_USER=heritrix"
      - "HERITRIX_PASSWORD=heritrix"
    hostname: tasks.heritrix-worker

  # 
  heritrix3-exporter:
    build: .
    #image: heritrix3exporter_heritrix3-exporter:latest
    ports:
      - 9119:9118
    environment:
      - "HERITRIX_USER=heritrix"
      - "HERITRIX_PASSWORD=heritrix"





