groups:
- name: example
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: high_load
    expr: avg(node_load1) by (instance) / count(node_cpu{mode="idle"}) by (instance) > 5.0
    for: 10m
    labels:
      severity: minor
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."

  - alert: predict_host_disk_space
    expr: min(predict_linear(node_filesystem_free{mountpoint=~"/|/data"}[48h], 2*7*24*3600)) by (instance, mountpoint) < 0
    for: 1h
    labels:
      severity: severe
    annotations:
      summary: "Disk space running out on {{ $labels.instance }} at {{ $labels.mountpoint }}"
      description: "Based on recent sampling, the disk is likely to will fill on volume {{ $labels.mountpoint }} within the next two weeks, for instance: {{ $labels.instance }}."
