groups:
- name: Core metrics
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: host_cpu_rate
    expr: 100 - 100*avg(irate(node_cpu_seconds_total{mode='idle'}[10m])) > 80
    for: 10m
    labels:
      severity: severe
    annotations:
      summary: "CPU rate on {{ $labels.instance }} > 80%"
      description: "CPU rate on {{ $labels.instance }} > 80% for more than 10 minutes"

  - alert: host_free_disk_space
    expr: (node_filesystem_avail_bytes{fstype=~"ext.|xfs|zfs"}/node_filesystem_size_bytes{fstype=~"ext.|xfs|zfs"}) * 100 < 15
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Disk space free < 15% on {{ $labels.instance }}"
      description: "Disk space free on {{ $labels.instance }} has been less that 15% for more than 5 minutes"
