# Global configuration for prometheus (within docker, not relevant to docker)
# scrape_interval controls frequency of scraping targets
# evaluation_interval controls how often the prometheus rules are evaluated against target data
global:
  scrape_interval:     1m
  evaluation_interval: 1m

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'syslog'
    static_configs:
      - targets: ['syslog:9100']
