# Global configuration for prometheus (within docker, not relevant to docker)
# scrape_interval controls frequency of scraping targets
# evaluation_interval controls how often the prometheus rules are evaluated against target data
global:
  scrape_interval:     1m
  evaluation_interval: 1m


# Specify the location of rules we want prometheus to load
rule_files:
  - 'alert.rules.yml'


# prometheus has a dependency on alertmanager, as defined in docker_compose.yml
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Define which resources prometheus should monitor
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['monitor:9090']

  - job_name: 'syslog'
    static_configs:
      - targets: ['syslog:9100']
