version: '3.2'

services:

  # Monitoring based on metrics (Prometheus + Grafana dashboard):
  # -------------------------------------------------------------

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
    volumes:
      - ./testing/grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - metrics-gateway:metrics-gateway
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    user: root
    volumes:
      - ./prometheus:/etc/prometheus
      - ./testing/prometheus-data:/prometheus
    extra_hosts:
      - "crawler01.n45.bl.uk:192.168.45.16"
      - "crawler02.n45.bl.uk:192.168.45.19"

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  metrics-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  apache-ukwa:
    image: garyritchie/apache_exporter
    command: './apache_exporter -scrape_uri "https://www.webarchive.org.uk/server-status/?auto"'
    ports:
      - 9117:9117

  # Providing system and container level metrics:
  # -------------------------------------------------------------

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

