version: '2'

services:

  # Monitoring based on metrics (Prometheus + Grafana dashboard):
  # -------------------------------------------------------------

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - metrics-gateway:metrics-gateway
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./testing/prometheus-data:/prometheus

  metrics-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./testing/grafana-data:/var/lib/grafana
