version: '3.2'

services:

  # Monitoring based on metrics (Prometheus + Grafana dashboard):
  # -------------------------------------------------------------

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_NAME=BL"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer"
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
    volumes:
      - ./testing/grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    depends_on:
      - alertmanager:alertmanager
      - metrics-gateway:metrics-gateway
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    user: root
    volumes:
      - ./prometheus:/etc/prometheus
      #- ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #- ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./testing/prometheus-data:/prometheus
    extra_hosts:
      - "access.wa:192.168.45.25"
      - "ingest:192.168.45.60"
      - "dev-monitor:192.168.45.101"
      - "crawler01:192.168.45.16"
      - "crawler02:192.168.45.19"
      - "crawler03:192.168.45.28"
      - "crawler04:192.168.45.12"
      - "bigcdx:192.168.45.21"
      - "solr1:192.168.1.71"
      - "solr2:192.168.1.72"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://dev-monitor.n45.wa.bl.uk:9090/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://dev-monitor.n45.wa.bl.uk:9093/'

  metrics-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox_exporter:/config
    command:
      - '--config.file=/config/config.yml'
    extra_hosts:
      - "ukwa-ui-beta:192.168.45.95"
      - "crawler03:192.168.45.28"
      - "access.wa:192.168.45.25"
      - "ingest:192.168.45.60"
      - "bigcdx:192.168.45.21"
      - "www.webarchive.org.uk:192.168.45.10"
      - "beta.webarchive.org.uk:192.168.45.10"

  apache-ukwa:
    image: garyritchie/apache_exporter
    command: './apache_exporter -scrape_uri "https://www.webarchive.org.uk/server-status/?auto"'
    ports:
      - 9117:9117

  uptimerobot-exporter:
    image: ukwa/uptimerobot-prometheus-exporter
    container_name: uptimerobot-exporter
    environment:
      - UPTIMEROBOT_API_KEY=${UPTIMEROBOT_API_KEY}
      - http_proxy=http://194.66.232.92:3127
    ports:
      - "9429:9429"

  # Providing system and container level metrics:
  # -------------------------------------------------------------

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

