global:
  scrape_interval:     30s
  evaluation_interval: 30s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'metrics-gateway'
    honor_labels: true
    static_configs:
      - targets: ['metrics-gateway:9091']

  - job_name: 'firefox-apache'
    static_configs:
      - targets: ['apache-ukwa:9117']

  - job_name: 'docker'
    static_configs:
      - targets: ['crawler01.n45.bl.uk:9323', 'crawler02.n45.bl.uk:9323']
