global:
  scrape_interval:     30s
  evaluation_interval: 30s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules.yml'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'metrics-gateway'
    honor_labels: true
    static_configs:
      - targets: ['metrics-gateway:9091']

  - job_name: 'firefox-apache'
    static_configs:
      - targets: ['apache-ukwa:9117']

  # See https://docs.docker.com/engine/admin/prometheus/
  - job_name: 'docker'
    static_configs:
      - targets: ['crawler01.n45.bl.uk:9323', 'crawler02.n45.bl.uk:9323']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://www.webarchive.org.uk/ukwa/
        - https://beta.webarchive.org.uk/
        - https://data.bl.uk/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter.
